### ISSUE TITLE
Do you need to have accesss to your Apple ID in order to find the device

### ISSUE THREAD

**Issue by shiprec** [hajekj/OfflineFindRecovery#1]
Hello @hajekj, love what you are building.  My question for you, after steps 1 and 2, **can you use any apple id (or do you even need an apple id)** for Step 3?  I ask as I have multiple accounts with tags and am looking for a way to track them all without having to cycle through each account.

Thank you!

**Comment by hajekj** [comment]
You can use any Apple ID to retrieve the tags (assuming you have the keys for it). Beware that the scripts in this repo [filter](https://github.com/hajekj/OfflineFindRecovery/blob/master/src/python/findmy-keygeneration.py#L50) only primary keys, and for AirTags you also need secondary keys.

For example, with my Apple ID, I retrieved tags for completely unrelated Apple device. From my understanding of the API, Apple is not linking (nor has the option, due to the privacy model) the location to the owning Apple ID. However, you need to have a valid Apple ID to retrieve the data.

**Comment by hajekj** [comment]
I have tried it only with MacOS, but I can certainly try iOS 17.3.1 (that's what my iPhone has now) and let you know.
